version: '3.7'
services:
  mysql:
    image: 'mysql:5.7'
    ports:
      - "12345:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/my_secret
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d/ 
    secrets:
      - my_secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=hot2018!
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8081:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"
    secrets:
      - my_secret
  
secrets:
  my_secret:
    file: ./sec.txt


